trigger:
  - master

#variables:
#  - name: PoolName
#    value: 'mycomputeragent'
#    readonly: true
#  - name: AgentName
#    value: 'CentOS9'
#    readonly: true
#
#pool: 
#  name: $(PoolName)
#  demands:
#    - agent.name -equals $(AgentName)
pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build and push Docker
        steps:
        
          - task: DownloadSecureFile@1
            name: configFile
            inputs:
              secureFile: 'config.json'

          - task: Docker@2
            inputs:
              containerRegistry: 'viodid-docker-hub'
              repository: 'calat33'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              arguments: '--build-arg="config_file=$(configFile.secureFilePath)"'
              
          - task: Docker@2
            inputs:
              containerRegistry: 'viodid-docker-hub'
              repository: 'calat33'
              command: 'push'
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
        - script: echo "deploying"
  - stage: Release
    jobs:
      - deployment: Release
        environment: 'my-environment'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "releasing"
