trigger:
  - master

#variables:
#  - name: PoolName
#    value: 'mycomputeragent'
#    readonly: true
#  - name: AgentName
#    value: 'CentOS9'
#    readonly: true
#
#pool: 
#  name: $(PoolName)
#  demands:
#    - agent.name -equals $(AgentName)
pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: Test
    jobs:
      - job: Test
        steps:
        - script: echo "testing"
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
        - script: echo "deploying"
  - stage: Release
    jobs:
      - deployment: Release
        environment: 'my-environment'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "releasing"
