trigger:
  - master

variables:
  - name: PoolName
    value: 'mycomputeragent'
    readonly: true
  - name: AgentName
    value: 'CentOS9'
    readonly: true

pool: 
  name: $(PoolName)
  demands:
    - agent.name -equals $(AgentName)


stages:
  - stage: Test
    jobs:
      - job: Test
        pool:
        vmImage: 'ubuntu-latest'
        steps:
        - script: echo "testing"
  - stage: Deploy
    jobs:
      - job: Deploy
        pool:
        vmImage: 'ubuntu-latest'
        steps:
        - script: echo "deploying"
  - stage: Release
    jobs:
      - deployment: Release
        pool:
        vmImage: 'ubuntu-latest'
        environment: 'my-environment'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "releasing"
