trigger:
  - master

variables:
  - group: "calart-vargroup"
#  - name: PoolName
#    value: 'mycomputeragent'
#    readonly: true
#  - name: AgentName
#    value: 'CentOS9'
#    readonly: true
#
#pool: 
#  name: $(PoolName)
#  demands:
#    - agent.name -equals $(AgentName)
pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build and push Docker
        steps:

          - task: Docker@2
            inputs:
              containerRegistry: 'viodid-docker-hub'
              repository: 'calat33'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              arguments: '--build-arg EMAIL_SENDER=$(EMAIL_SENDER) --build-arg EMAIL_PASSWORD=$(EMAIL_PASSWORD)'
              
          - task: Docker@2
            inputs:
              containerRegistry: 'viodid-docker-hub'
              repository: 'calat33'
              command: 'push'
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
        - script: echo "deploying"
  - stage: Release
    jobs:
      - deployment: Release
        environment: 'my-environment'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: echo "releasing"
